title : void ★★
tagline: this is the [acting] tagline
author :
  name : Igor Okulist
  email : igor@okulist.com
  github : okigan

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
